import type { Metadata } from 'next';
import './globals.css';
import App from '@/shared/componenets/App';

export const metadata: Metadata = {
  title: 'Retrofit V3',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <App>{children}</App>
      </body>
    </html>
  );
}
